service: app

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2

plugins:
  - ./vendor/bref/bref
  - serverless-lift
functions:
    api:
        handler: index.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-80-fpm}
        events:
            -   httpApi: '*'

constructs:
  website:
    type: server-side-website
    domain: vegvizir.com
    certificate: arn:aws:acm:us-east-1:570617718140:certificate/bbd34241-b843-44ac-a43e-d1b3a64e74b1
    assets:
      '/js/*': assets/js
      '/css/*': assets/css
      '/favicon.ico': assets/favicon.ico
      '/robots.txt': assets/robots.txt
      # add here any file or directory that needs to be served from S3

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
